apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: addons
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: https://github.com/fmbahrt/dinglebop-io.git
        revision: HEAD
        directories:
          - path: gitops/addons/*/*
  template:
    metadata:
      name: "{{path[1]}}"
    spec:
      project: default
      source:
        repoURL: https://github.com/fmbahrt/dinglebop-io.git
        targetRevision: HEAD
        path: "{{path}}"
      destination:
        name: "{{path[2]}}"
        namespace: "{{path[1]}}"
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
