apiVersion: v2
name: cert-manager-subchart
version: 1.0.0
dependencies:
  - name: cert-manager
    version: v1.20.2
    repository: https://charts.jetstack.io
  - name: raw
    version: 2.0.2
    repository: https://bedag.github.io/helm-charts
