raw:
  resources:
    - apiVersion: gateway.networking.k8s.io/v1
      kind: Gateway
      metadata:
        name: cluster-gateway
        namespace: agentgateway
      annotations:
        cert-manager.io/issuer: letsencrypt
      spec:
        gatewayClassName: agentgateway
        allowedListeners:
          namespaces:
            from: All
        listeners:
          - protocol: HTTP
            port: 80
            name: http
            hostname: "*.dingle.bop"
            allowedRoutes:
              namespaces:
                from: All
          - protocol: HTTP
            port: 80
            name: http-public
            hostname: dinglebop.io
            allowedRoutes:
              namespaces:
                from: All
          - protocol: HTTPS
            port: 443
            name: https
            hostname: dinglebop.io
            allowedRoutes:
              namespaces:
                from: All
            tls:
              mode: Terminate
              certificateRefs:
                - name: dinglebop-io-tls
